import { drizzle } from 'drizzle-orm/node-postgres'
import { Client } from 'pg'
import { recipes, nutrition, ingredients, tips, categories } from './schema'
import * as dotenv from 'dotenv'
dotenv.config()

// Use Client (single connection) instead of Pool to avoid SSL cert rotation issues
const connectionString = (process.env.DATABASE_URL || '').replace('sslmode=require', 'sslmode=no-verify')
const client = new Client({ connectionString, ssl: { rejectUnauthorized: false } })
const db = drizzle(client)

const recipeData = [
    { title: 'Chicken Karahi', description: 'Classic Pakistani tomato-based chicken curry', instructions: 'Step 1: Heat 3 tablespoons of oil in a heavy-bottomed wok or karahi over high heat until it shimmers.\nStep 2: Add 1 kg bone-in chicken pieces and fry on high heat for 8–10 minutes, turning occasionally, until golden brown on all sides.\nStep 3: Add 1 tablespoon each of ginger paste and garlic paste. Stir constantly for 2 minutes until the raw smell disappears.\nStep 4: Add 4 medium tomatoes (chopped) along with 1 teaspoon red chili powder, 1 teaspoon cumin, half teaspoon turmeric, and salt to taste.\nStep 5: Cover and cook on medium heat for 10 minutes until tomatoes break down completely into a thick masala.\nStep 6: Uncover and cook on high heat, stirring frequently, until the oil separates and rises to the top — this is the key sign the masala is ready.\nStep 7: Add 2 green chilies (slit) and 1 tablespoon fresh ginger julienne. Stir for 1 minute.\nStep 8: Garnish with fresh coriander and serve hot with naan or roti.', imageUrl: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600', cookingTime: 35, costLevel: 'Medium', category: 'High Protein', isZeroWaste: false, sustainabilityTip: 'Use leftover bones for broth', ingredients: 'Chicken, Tomato, Ginger, Garlic, Oil, Spices', seoTitle: 'Chicken Karahi Recipe', seoDescription: 'Authentic Pakistani chicken karahi', seoKeywords: 'chicken karahi, pakistani recipe' },
    { title: 'Daal Chawal', description: 'Comforting lentil soup with rice', instructions: 'Step 1: Rinse 1 cup of red lentils (masoor daal) under cold water until the water runs clear.\nStep 2: In a pot, combine lentils with 3 cups of water, half teaspoon turmeric, and a pinch of salt. Bring to a boil.\nStep 3: Reduce heat to medium-low, cover, and simmer for 20 minutes until lentils are completely soft and mushy. Stir occasionally.\nStep 4: Meanwhile, cook 1.5 cups of basmati rice separately: rinse, soak 15 minutes, then cook with 2.5 cups water until fluffy.\nStep 5: For the tarka, heat 2 tablespoons of ghee or oil in a small pan over medium-high heat.\nStep 6: Add 1 medium onion (thinly sliced) and fry until deep golden brown, about 8 minutes.\nStep 7: Add 1 teaspoon cumin seeds, 2 dried red chilies, and 1 teaspoon garlic paste. Fry for 30 seconds.\nStep 8: Add 1 chopped tomato and cook for 3 minutes until soft. Pour the entire tarka over the cooked lentils, stir, and serve over rice.', imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600', cookingTime: 30, costLevel: 'Low', category: 'Budget Friendly', isZeroWaste: true, sustainabilityTip: 'Lentils have a very low carbon footprint', ingredients: 'Lentils, Rice, Onion, Tomato, Cumin, Turmeric', seoTitle: 'Daal Chawal Recipe', seoDescription: 'Simple and nutritious lentil rice', seoKeywords: 'daal chawal, lentil rice' },
    { title: 'Vegetable Stir Fry', description: 'Quick and healthy mixed vegetable stir fry', instructions: 'Step 1: Prepare all vegetables before you start cooking — this dish moves fast. Slice 1 carrot into thin matchsticks, cut 1 cup broccoli into small florets, and julienne 1 red bell pepper.\nStep 2: Mix the sauce: 2 tablespoons soy sauce, 1 tablespoon oyster sauce, 1 teaspoon sesame oil, 1 teaspoon cornstarch, and 2 tablespoons water. Set aside.\nStep 3: Heat a wok or large pan over the highest heat possible until it begins to smoke slightly.\nStep 4: Add 2 tablespoons of oil and immediately add 3 minced garlic cloves. Stir for 15 seconds — do not let it burn.\nStep 5: Add carrots first (they take longest) and stir fry for 2 minutes, tossing constantly.\nStep 6: Add broccoli and bell pepper. Stir fry for another 3 minutes, keeping everything moving.\nStep 7: Pour the sauce over the vegetables and toss to coat evenly. Cook for 1 more minute until the sauce thickens and glazes the vegetables.\nStep 8: Remove from heat immediately and serve over steamed rice or noodles.', imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600', cookingTime: 15, costLevel: 'Low', category: 'Quick Fix', isZeroWaste: true, sustainabilityTip: 'Use any leftover vegetables from your fridge', ingredients: 'Carrot, Broccoli, Bell Pepper, Soy Sauce, Garlic, Oil', seoTitle: 'Vegetable Stir Fry', seoDescription: 'Quick healthy stir fry recipe', seoKeywords: 'stir fry, vegetables, healthy' },
    { title: 'Egg Fried Rice', description: 'Classic fried rice with eggs and vegetables', instructions: 'Step 1: Use day-old cooked rice if possible — fresh rice is too moist and will clump. If using fresh, spread it on a tray and refrigerate for 30 minutes.\nStep 2: Beat 3 eggs with a pinch of salt and set aside.\nStep 3: Heat 1 tablespoon of oil in a wok over high heat. Pour in the eggs and scramble quickly, breaking into small pieces. Remove and set aside.\nStep 4: Add another tablespoon of oil to the same wok. Add 2 minced garlic cloves and fry for 20 seconds.\nStep 5: Add 1 diced carrot and half cup of peas. Stir fry for 3 minutes until slightly tender.\nStep 6: Add the cold rice, breaking up any clumps with a spatula. Press the rice against the hot wok surface and let it sit for 30 seconds to get slightly crispy, then toss.\nStep 7: Add 2 tablespoons soy sauce and 1 teaspoon sesame oil. Toss everything together for 2 minutes.\nStep 8: Return the scrambled eggs to the wok, mix well, taste for seasoning, and serve immediately garnished with spring onions.', imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600', cookingTime: 20, costLevel: 'Low', category: 'Budget Friendly', isZeroWaste: true, sustainabilityTip: 'Perfect for day-old leftover rice', ingredients: 'Rice, Eggs, Carrot, Peas, Soy Sauce, Garlic', seoTitle: 'Egg Fried Rice Recipe', seoDescription: 'Easy egg fried rice with vegetables', seoKeywords: 'fried rice, egg, quick meal' },
    { title: 'Grilled Chicken Salad', description: 'Fresh salad with grilled chicken breast', instructions: 'Step 1: Pound 2 chicken breasts to an even thickness of about 1.5 cm — this ensures even cooking.\nStep 2: Marinate the chicken: mix 2 tablespoons olive oil, juice of 1 lemon, 1 teaspoon garlic powder, 1 teaspoon dried oregano, salt and pepper. Coat the chicken and let it sit for at least 15 minutes.\nStep 3: Heat a grill pan or outdoor grill over medium-high heat. Brush with a little oil.\nStep 4: Grill the chicken for 6–7 minutes per side without moving it — this creates proper grill marks and seals in the juices.\nStep 5: Let the chicken rest for 5 minutes before slicing. This is crucial — cutting too early loses all the juices.\nStep 6: While chicken rests, prepare the salad base: tear 2 cups of romaine lettuce, slice 1 cucumber, halve 10 cherry tomatoes, and thinly slice half a red onion.\nStep 7: Make the dressing: whisk 3 tablespoons olive oil, 1.5 tablespoons lemon juice, 1 teaspoon Dijon mustard, salt and pepper.\nStep 8: Slice the chicken diagonally, arrange over the salad, drizzle with dressing, and serve immediately.', imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600', cookingTime: 25, costLevel: 'Medium', category: 'High Protein', isZeroWaste: false, sustainabilityTip: 'Use leftover chicken from previous meals', ingredients: 'Chicken Breast, Lettuce, Tomato, Cucumber, Olive Oil, Lemon', seoTitle: 'Grilled Chicken Salad', seoDescription: 'Healthy grilled chicken salad recipe', seoKeywords: 'chicken salad, healthy, protein' },
]

const moreRecipes = [
    { title: 'Banana Oat Pancakes', description: 'Healthy pancakes made with banana and oats', instructions: 'Step 1: Blend 1 cup of rolled oats in a blender until they form a fine flour-like powder.\nStep 2: Mash 2 very ripe bananas in a large bowl until completely smooth with no lumps.\nStep 3: Add the oat flour, 2 eggs, half teaspoon cinnamon, 1 teaspoon vanilla extract, and a pinch of salt to the mashed banana. Mix until a thick batter forms.\nStep 4: If the batter is too thick, add 2–3 tablespoons of milk to loosen it slightly.\nStep 5: Heat a non-stick pan over medium heat and lightly grease with a small amount of butter or coconut oil.\nStep 6: Pour about 3 tablespoons of batter per pancake. Cook for 2–3 minutes until bubbles form on the surface and the edges look set.\nStep 7: Flip carefully and cook for another 1–2 minutes until golden brown. These pancakes are more delicate than regular ones, so flip gently.\nStep 8: Serve stacked with a drizzle of honey, fresh berries, or a dollop of Greek yogurt.', imageUrl: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=600', cookingTime: 15, costLevel: 'Low', category: 'Budget Friendly', isZeroWaste: true, sustainabilityTip: 'Use overripe bananas that would otherwise be thrown away', ingredients: 'Banana, Oats, Egg, Honey, Cinnamon', seoTitle: 'Banana Oat Pancakes', seoDescription: 'Healthy banana oat pancakes recipe', seoKeywords: 'pancakes, banana, healthy breakfast' },
    { title: 'Spinach Smoothie', description: 'Green power smoothie with spinach and banana', instructions: 'Step 1: Add 2 large handfuls of fresh spinach to the blender first — placing it at the bottom helps it blend more smoothly.\nStep 2: Add 1 ripe banana (frozen works best for a thicker, colder smoothie), 1 cup of cold milk or plant-based milk, and 1 tablespoon of honey.\nStep 3: Add 1 tablespoon of chia seeds for extra fiber and omega-3s.\nStep 4: Optionally add half an avocado for creaminess and healthy fats.\nStep 5: Blend on high speed for 60 seconds until completely smooth. Stop and scrape down the sides if needed.\nStep 6: Taste and adjust sweetness with more honey if desired.\nStep 7: Pour into a tall glass and serve immediately — the smoothie will separate if left standing.\nStep 8: For extra nutrition, top with a sprinkle of chia seeds or granola.', imageUrl: 'https://images.unsplash.com/photo-1610970881699-44a5587cabec?w=600', cookingTime: 5, costLevel: 'Low', category: 'Quick Fix', isZeroWaste: true, sustainabilityTip: 'Use wilted spinach that is still nutritious', ingredients: 'Spinach, Banana, Milk, Honey, Chia Seeds', seoTitle: 'Spinach Smoothie', seoDescription: 'Nutritious green spinach smoothie', seoKeywords: 'smoothie, spinach, green drink' },
    { title: 'Lentil Soup', description: 'Hearty and warming red lentil soup', instructions: 'Step 1: Rinse 1.5 cups of red lentils thoroughly under cold water until the water runs clear.\nStep 2: Heat 2 tablespoons of olive oil in a large pot over medium heat. Add 1 large diced onion and cook for 6–7 minutes until soft and translucent.\nStep 3: Add 3 minced garlic cloves, 1 teaspoon ground cumin, 1 teaspoon turmeric, and half teaspoon smoked paprika. Stir for 1 minute until fragrant.\nStep 4: Add the rinsed lentils and 5 cups of vegetable broth. Bring to a boil.\nStep 5: Reduce heat to medium-low, cover, and simmer for 20–25 minutes until lentils are completely soft and falling apart.\nStep 6: Use an immersion blender to partially blend the soup — blend about half of it to create a creamy texture while keeping some lentils whole for body.\nStep 7: Squeeze in the juice of half a lemon, taste, and adjust salt and spices.\nStep 8: Serve hot with a swirl of olive oil, a pinch of paprika, and crusty bread on the side.', imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600', cookingTime: 30, costLevel: 'Low', category: 'Zero Waste', isZeroWaste: true, sustainabilityTip: 'Lentils require 50x less water than beef', ingredients: 'Red Lentils, Onion, Garlic, Cumin, Turmeric, Lemon', seoTitle: 'Red Lentil Soup', seoDescription: 'Warming red lentil soup recipe', seoKeywords: 'lentil soup, vegan, healthy' },
    { title: 'Avocado Toast', description: 'Simple and nutritious avocado on sourdough', instructions: 'Step 1: Toast 2 thick slices of sourdough bread until golden and crispy. The bread should be sturdy enough to hold the toppings.\nStep 2: While the bread toasts, halve 1 ripe avocado, remove the pit, and scoop the flesh into a bowl.\nStep 3: Add the juice of half a lemon, a pinch of salt, and a pinch of red chili flakes. Mash with a fork to your preferred texture — some like it chunky, others prefer it smooth.\nStep 4: Taste the avocado mixture and adjust seasoning. It should be bright and well-seasoned.\nStep 5: Spread the mashed avocado generously over the toasted bread, going all the way to the edges.\nStep 6: Optional but recommended: fry or poach 1–2 eggs and place on top for extra protein.\nStep 7: Finish with a drizzle of good olive oil, extra chili flakes, and a few flakes of sea salt.\nStep 8: Serve immediately — avocado toast waits for no one.', imageUrl: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c820?w=600', cookingTime: 10, costLevel: 'Medium', category: 'Quick Fix', isZeroWaste: false, sustainabilityTip: 'Use the avocado pit to grow a new plant', ingredients: 'Avocado, Sourdough Bread, Lemon, Salt, Chili Flakes', seoTitle: 'Avocado Toast Recipe', seoDescription: 'Classic avocado toast with toppings', seoKeywords: 'avocado toast, breakfast, healthy' },
    { title: 'Chickpea Curry', description: 'Creamy vegan chickpea curry with coconut milk', instructions: 'Step 1: Heat 2 tablespoons of oil in a large pan over medium heat. Add 1 large diced onion and cook for 8 minutes until golden.\nStep 2: Add 1 tablespoon ginger paste and 1 tablespoon garlic paste. Cook for 2 minutes, stirring constantly.\nStep 3: Add 1 teaspoon each of cumin, coriander, turmeric, and garam masala, plus half teaspoon chili powder. Stir the spices into the onion for 1 minute.\nStep 4: Add 2 chopped tomatoes and cook for 5 minutes until they break down into a thick paste.\nStep 5: Drain and rinse 2 cans (400g each) of chickpeas and add to the pan. Stir to coat with the masala.\nStep 6: Pour in 1 can (400ml) of full-fat coconut milk. Stir well and bring to a gentle simmer.\nStep 7: Simmer uncovered for 15 minutes, stirring occasionally, until the sauce thickens and the chickpeas absorb the flavors.\nStep 8: Finish with a squeeze of lemon juice and fresh coriander. Serve with basmati rice or warm naan.', imageUrl: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600', cookingTime: 25, costLevel: 'Low', category: 'Vegan', isZeroWaste: true, sustainabilityTip: 'Chickpeas fix nitrogen in soil — great for the planet', ingredients: 'Chickpeas, Coconut Milk, Tomato, Onion, Garam Masala, Ginger', seoTitle: 'Chickpea Curry', seoDescription: 'Easy vegan chickpea curry recipe', seoKeywords: 'chickpea curry, vegan, plant based' },
    { title: 'Pasta Aglio e Olio', description: 'Simple Italian pasta with garlic and olive oil', instructions: 'Step 1: Bring a large pot of water to a rolling boil. Add a generous amount of salt — it should taste like the sea.\nStep 2: Cook 400g of spaghetti or linguine according to package instructions until al dente (firm to the bite). Reserve 1 cup of pasta cooking water before draining.\nStep 3: While pasta cooks, thinly slice 6–8 garlic cloves. The thinner the slices, the more evenly they will cook.\nStep 4: Heat 6 tablespoons of good quality olive oil in a large pan over medium-low heat. Add the garlic slices and cook slowly for 4–5 minutes until golden and fragrant. Watch carefully — burnt garlic will ruin the dish.\nStep 5: Add half teaspoon of red chili flakes and stir for 30 seconds.\nStep 6: Add the drained pasta directly to the pan. Toss vigorously to coat every strand with the garlic oil.\nStep 7: Add pasta water a splash at a time, tossing continuously, until the sauce emulsifies and clings to the pasta.\nStep 8: Remove from heat, add a large handful of fresh parsley and a generous grating of Parmesan. Toss once more and serve immediately.', imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=600', cookingTime: 20, costLevel: 'Low', category: 'Budget Friendly', isZeroWaste: false, sustainabilityTip: 'Save pasta water to thicken the sauce', ingredients: 'Pasta, Garlic, Olive Oil, Parsley, Chili Flakes, Parmesan', seoTitle: 'Pasta Aglio e Olio', seoDescription: 'Classic Italian garlic pasta recipe', seoKeywords: 'pasta, italian, garlic, quick' },
    { title: 'Overnight Oats', description: 'No-cook oats prepared the night before', instructions: 'Step 1: Add half cup of rolled oats to a jar or container with a lid. Use old-fashioned rolled oats, not instant — they hold their texture better overnight.\nStep 2: Pour in half cup of milk (dairy or plant-based) and 3 tablespoons of Greek yogurt. The yogurt adds creaminess and protein.\nStep 3: Add 1 tablespoon of chia seeds — they will absorb liquid and create a pudding-like texture.\nStep 4: Sweeten with 1 tablespoon of honey or maple syrup and add half teaspoon of vanilla extract.\nStep 5: Stir everything together thoroughly, making sure the oats are fully submerged in the liquid.\nStep 6: Seal the jar and refrigerate overnight, or for at least 6 hours. The oats will absorb the liquid and soften completely.\nStep 7: In the morning, give it a good stir. If it is too thick, add a splash of milk to loosen.\nStep 8: Top with sliced banana, fresh berries, a drizzle of honey, and a sprinkle of granola for crunch. Eat cold straight from the jar.', imageUrl: 'https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=600', cookingTime: 5, costLevel: 'Low', category: 'Quick Fix', isZeroWaste: true, sustainabilityTip: 'Oats have one of the lowest carbon footprints of any food', ingredients: 'Oats, Milk, Banana, Berries, Honey, Chia Seeds', seoTitle: 'Overnight Oats Recipe', seoDescription: 'Easy overnight oats for busy mornings', seoKeywords: 'overnight oats, breakfast, meal prep' },
    { title: 'Tuna Salad Wrap', description: 'Protein-packed tuna wrap with fresh vegetables', instructions: 'Step 1: Drain 1 can (185g) of tuna thoroughly — press the lid against the tuna to squeeze out as much liquid as possible.\nStep 2: In a bowl, combine the tuna with 2 tablespoons of mayonnaise, 1 teaspoon of Dijon mustard, and a squeeze of lemon juice. Mix well.\nStep 3: Add 2 tablespoons of finely diced red onion, 1 tablespoon of capers (optional), and salt and pepper to taste. Mix again.\nStep 4: Warm a large flour tortilla in a dry pan for 30 seconds per side, or microwave for 15 seconds — this makes it more pliable and prevents cracking.\nStep 5: Lay the tortilla flat and spread the tuna mixture in a line down the center, leaving 5 cm clear at each end.\nStep 6: Add a layer of crisp lettuce leaves, sliced tomato, and thinly sliced cucumber on top of the tuna.\nStep 7: Fold in the sides of the tortilla, then roll tightly from the bottom up, keeping the filling compact.\nStep 8: Slice diagonally in half and serve immediately, or wrap tightly in foil for a packed lunch.', imageUrl: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=600', cookingTime: 10, costLevel: 'Medium', category: 'High Protein', isZeroWaste: false, sustainabilityTip: 'Choose sustainably sourced tuna', ingredients: 'Tuna, Tortilla, Lettuce, Tomato, Mayo, Lemon', seoTitle: 'Tuna Salad Wrap', seoDescription: 'Quick and healthy tuna wrap recipe', seoKeywords: 'tuna wrap, protein, lunch' },
    { title: 'Mushroom Risotto', description: 'Creamy Italian risotto with mushrooms', instructions: 'Step 1: Warm 1 litre of vegetable or chicken broth in a separate pot and keep it on low heat. Adding cold broth to risotto shocks the rice and ruins the texture.\nStep 2: In a large wide pan, heat 2 tablespoons of butter over medium heat. Add 300g of sliced mushrooms and cook for 6–8 minutes until golden and all moisture has evaporated. Season with salt and set aside.\nStep 3: In the same pan, add 1 tablespoon of olive oil and cook 1 finely diced onion for 5 minutes until soft.\nStep 4: Add 300g of arborio rice and stir for 2 minutes until the grains are coated and slightly translucent at the edges.\nStep 5: Pour in 100ml of dry white wine and stir until fully absorbed.\nStep 6: Begin adding the warm broth one ladle at a time, stirring constantly and waiting until each ladle is absorbed before adding the next. This process takes 18–20 minutes.\nStep 7: When the rice is creamy and al dente, stir in the cooked mushrooms, 50g of grated Parmesan, and 1 tablespoon of cold butter. Stir vigorously — this is called mantecatura and creates the signature creaminess.\nStep 8: Remove from heat, cover for 2 minutes, then serve immediately with extra Parmesan and fresh thyme.', imageUrl: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=600', cookingTime: 40, costLevel: 'Medium', category: 'Vegan', isZeroWaste: true, sustainabilityTip: 'Use mushroom stems in the broth', ingredients: 'Arborio Rice, Mushrooms, Onion, White Wine, Parmesan, Butter', seoTitle: 'Mushroom Risotto', seoDescription: 'Creamy mushroom risotto recipe', seoKeywords: 'risotto, mushroom, italian' },
    { title: 'Black Bean Tacos', description: 'Crispy tacos filled with spiced black beans', instructions: 'Step 1: Drain and rinse 1 can (400g) of black beans. Pat them dry with a paper towel — drier beans will season better.\nStep 2: Heat 1 tablespoon of oil in a pan over medium heat. Add half a diced onion and cook for 4 minutes.\nStep 3: Add 2 minced garlic cloves, 1 teaspoon cumin, 1 teaspoon smoked paprika, and half teaspoon chili powder. Stir for 1 minute.\nStep 4: Add the black beans and 3 tablespoons of water. Mash about half the beans with the back of a spoon to create a creamy texture while keeping some whole. Cook for 5 minutes.\nStep 5: Season with salt, pepper, and a squeeze of lime juice. The filling should be thick and well-seasoned.\nStep 6: Warm corn tortillas directly over a gas flame for 20 seconds per side until slightly charred, or in a dry pan.\nStep 7: Assemble the tacos: spoon the bean mixture onto each tortilla, then top with diced avocado, fresh salsa, shredded cabbage, and a squeeze of lime.\nStep 8: Finish with fresh cilantro and a drizzle of hot sauce. Serve immediately while the tortillas are still warm.', imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600', cookingTime: 20, costLevel: 'Low', category: 'Vegan', isZeroWaste: true, sustainabilityTip: 'Beans produce 50x less CO2 than beef', ingredients: 'Black Beans, Corn Tortillas, Avocado, Salsa, Lime, Cilantro', seoTitle: 'Black Bean Tacos', seoDescription: 'Easy vegan black bean tacos', seoKeywords: 'tacos, vegan, black beans' },
]

const evenMoreRecipes = [
    { title: 'Greek Yogurt Bowl', description: 'Protein-rich yogurt bowl with fruits and granola', instructions: 'Step 1: Choose a thick, full-fat Greek yogurt for the best texture and flavor — it should be creamy and slightly tangy.\nStep 2: Spoon 200g of Greek yogurt into a wide bowl. Use the back of the spoon to spread it slightly toward the edges.\nStep 3: Slice 1 ripe banana and arrange the slices in a fan pattern on one side of the bowl.\nStep 4: Add a handful of mixed fresh berries (strawberries, blueberries, raspberries) on the other side.\nStep 5: Sprinkle 3–4 tablespoons of granola over the center for crunch. Add it just before eating so it stays crispy.\nStep 6: Drizzle 1 tablespoon of raw honey in a zigzag pattern over the entire bowl.\nStep 7: Add a sprinkle of chia seeds or flaxseeds for extra nutrition.\nStep 8: Optionally add a pinch of cinnamon or a few crushed walnuts. Serve immediately and enjoy the contrast of creamy, crunchy, and fruity.', imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600', cookingTime: 5, costLevel: 'Medium', category: 'High Protein', isZeroWaste: false, sustainabilityTip: 'Buy local seasonal fruits', ingredients: 'Greek Yogurt, Granola, Berries, Honey, Banana', seoTitle: 'Greek Yogurt Bowl', seoDescription: 'Healthy yogurt bowl with fruits', seoKeywords: 'yogurt bowl, breakfast, protein' },
    { title: 'Vegetable Soup', description: 'Hearty mixed vegetable soup', instructions: 'Step 1: Prepare your vegetables: dice 2 carrots, 2 potatoes, 2 celery stalks, 1 large onion, and 2 tomatoes into roughly equal 1.5 cm pieces.\nStep 2: Heat 2 tablespoons of olive oil in a large pot over medium heat. Add the onion and celery and cook for 5 minutes until softened.\nStep 3: Add 3 minced garlic cloves and cook for 1 minute until fragrant.\nStep 4: Add the carrots and potatoes, stir to coat with the oil, and cook for 3 minutes.\nStep 5: Add the tomatoes, 1.5 litres of vegetable broth, 1 bay leaf, 1 teaspoon dried thyme, and salt and pepper.\nStep 6: Bring to a boil, then reduce heat to medium-low. Cover and simmer for 25 minutes until all vegetables are completely tender.\nStep 7: Taste and adjust seasoning. For a richer flavor, stir in 1 tablespoon of tomato paste.\nStep 8: Remove the bay leaf, ladle into bowls, and serve with crusty bread. The soup tastes even better the next day.', imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600', cookingTime: 35, costLevel: 'Low', category: 'Zero Waste', isZeroWaste: true, sustainabilityTip: 'Use vegetable scraps to make the broth', ingredients: 'Carrot, Potato, Celery, Onion, Tomato, Broth', seoTitle: 'Vegetable Soup', seoDescription: 'Hearty zero waste vegetable soup', seoKeywords: 'vegetable soup, zero waste, healthy' },
    { title: 'Salmon with Lemon', description: 'Pan-seared salmon with lemon butter sauce', instructions: 'Step 1: Remove the salmon from the fridge 15 minutes before cooking — cooking cold fish leads to uneven results.\nStep 2: Pat the salmon fillets completely dry with paper towels. Moisture is the enemy of a good sear. Season generously with salt and pepper on both sides.\nStep 3: Heat 1 tablespoon of oil in a heavy pan (cast iron is ideal) over medium-high heat until it just begins to smoke.\nStep 4: Place the salmon skin-side down and press gently with a spatula for the first 30 seconds to prevent curling. Cook for 4 minutes without moving.\nStep 5: Flip the salmon and cook for another 2–3 minutes. The fish is done when it flakes easily and the center is just barely opaque.\nStep 6: Remove the salmon and reduce heat to medium. Add 2 tablespoons of butter to the pan.\nStep 7: Once the butter melts and begins to foam, add 2 minced garlic cloves and cook for 30 seconds. Add the juice of 1 lemon and 1 tablespoon of fresh dill.\nStep 8: Spoon the lemon butter sauce over the salmon and serve immediately with steamed vegetables or roasted potatoes.', imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=600', cookingTime: 20, costLevel: 'High', category: 'High Protein', isZeroWaste: false, sustainabilityTip: 'Choose sustainably farmed salmon', ingredients: 'Salmon, Lemon, Butter, Garlic, Dill, Salt', seoTitle: 'Pan Seared Salmon', seoDescription: 'Easy pan seared salmon recipe', seoKeywords: 'salmon, fish, high protein' },
    { title: 'Hummus with Pita', description: 'Homemade creamy hummus with warm pita', instructions: 'Step 1: Drain and rinse 1 can (400g) of chickpeas. For the smoothest hummus, remove the skins by rubbing the chickpeas between your hands — this step is optional but makes a big difference.\nStep 2: In a food processor, combine the chickpeas, 3 tablespoons of tahini, juice of 1.5 lemons, 1 small garlic clove, and half teaspoon of salt.\nStep 3: Process for 1 minute, then with the machine running, slowly drizzle in 3–4 tablespoons of ice-cold water. The cold water makes the hummus lighter and fluffier.\nStep 4: Continue processing for 3–4 minutes total until the hummus is completely smooth and creamy. Taste and adjust lemon, salt, and garlic.\nStep 5: Transfer to a serving bowl and use the back of a spoon to create a shallow well in the center.\nStep 6: Drizzle generously with good quality olive oil, sprinkle with smoked paprika, and add a few whole chickpeas for garnish.\nStep 7: Warm pita bread in a dry pan or oven for 2 minutes until soft and slightly puffed.\nStep 8: Serve the hummus with warm pita, sliced vegetables, and olives on the side.', imageUrl: 'https://images.unsplash.com/photo-1577805947697-89e18249d767?w=600', cookingTime: 10, costLevel: 'Low', category: 'Vegan', isZeroWaste: true, sustainabilityTip: 'Use aquafaba (chickpea water) in other recipes', ingredients: 'Chickpeas, Tahini, Lemon, Garlic, Olive Oil, Pita', seoTitle: 'Homemade Hummus', seoDescription: 'Easy homemade hummus recipe', seoKeywords: 'hummus, vegan, snack' },
    { title: 'Beef Stir Fry', description: 'Quick beef and vegetable stir fry', instructions: 'Step 1: Slice 400g of beef (sirloin or flank steak) against the grain into thin strips, about 3mm thick. Slicing against the grain shortens the muscle fibers and makes the beef tender.\nStep 2: Marinate the beef: mix 1 tablespoon soy sauce, 1 teaspoon cornstarch, 1 teaspoon sesame oil, and a pinch of baking soda. Toss with the beef and let sit for 15 minutes. The baking soda tenderizes the meat.\nStep 3: Make the sauce: combine 3 tablespoons soy sauce, 1 tablespoon oyster sauce, 1 teaspoon sugar, 1 teaspoon cornstarch, and 2 tablespoons water.\nStep 4: Heat a wok over the highest heat possible until smoking. Add 2 tablespoons of oil.\nStep 5: Add the beef in a single layer and do not stir for 1 minute — let it sear. Then stir fry for another minute until just cooked. Remove and set aside.\nStep 6: Add another tablespoon of oil to the wok. Add 1 tablespoon each of minced ginger and garlic. Stir for 20 seconds.\nStep 7: Add 2 cups of broccoli florets and 1 sliced bell pepper. Stir fry for 3 minutes.\nStep 8: Return the beef to the wok, pour in the sauce, and toss everything together for 1 minute until the sauce thickens and coats everything. Serve over steamed rice.', imageUrl: 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=600', cookingTime: 20, costLevel: 'High', category: 'High Protein', isZeroWaste: false, sustainabilityTip: 'Use smaller portions of beef to reduce carbon footprint', ingredients: 'Beef, Broccoli, Bell Pepper, Soy Sauce, Ginger, Garlic', seoTitle: 'Beef Stir Fry', seoDescription: 'Quick beef stir fry recipe', seoKeywords: 'beef stir fry, protein, quick' },
    { title: 'Tomato Basil Pasta', description: 'Fresh tomato pasta with basil', instructions: 'Step 1: Bring a large pot of heavily salted water to a boil. Cook 400g of pasta (spaghetti or penne) until al dente. Reserve 1 cup of pasta water before draining.\nStep 2: While pasta cooks, score an X on the bottom of 6 ripe tomatoes. Blanch in boiling water for 30 seconds, then transfer to ice water. Peel, deseed, and roughly chop.\nStep 3: Heat 4 tablespoons of olive oil in a large pan over medium heat. Add 4 minced garlic cloves and cook for 1–2 minutes until fragrant but not browned.\nStep 4: Add the chopped tomatoes, a pinch of sugar (to balance acidity), salt, and pepper. Cook for 10 minutes until the tomatoes break down into a chunky sauce.\nStep 5: Tear a large handful of fresh basil leaves and add half to the sauce. Stir and cook for 1 more minute.\nStep 6: Add the drained pasta to the sauce and toss vigorously. Add pasta water a splash at a time until the sauce coats every strand.\nStep 7: Remove from heat and add the remaining fresh basil.\nStep 8: Serve in warm bowls with a generous grating of Parmesan, a drizzle of olive oil, and extra basil on top.', imageUrl: 'https://images.unsplash.com/photo-1598866594230-a7c12756260f?w=600', cookingTime: 20, costLevel: 'Low', category: 'Budget Friendly', isZeroWaste: false, sustainabilityTip: 'Grow your own basil on a windowsill', ingredients: 'Pasta, Tomatoes, Basil, Garlic, Olive Oil, Parmesan', seoTitle: 'Tomato Basil Pasta', seoDescription: 'Simple tomato basil pasta recipe', seoKeywords: 'pasta, tomato, basil, italian' },
    { title: 'Carrot Ginger Soup', description: 'Silky smooth carrot and ginger soup', instructions: 'Step 1: Preheat oven to 200°C. Peel and roughly chop 700g of carrots. Toss with 1 tablespoon of olive oil, salt, and pepper. Spread on a baking tray and roast for 25 minutes until caramelized at the edges.\nStep 2: While carrots roast, heat 1 tablespoon of oil in a large pot over medium heat. Add 1 large diced onion and cook for 6 minutes until soft.\nStep 3: Add 2 tablespoons of freshly grated ginger and 2 minced garlic cloves. Cook for 2 minutes, stirring constantly.\nStep 4: Add the roasted carrots to the pot along with 1 litre of vegetable broth. Bring to a simmer.\nStep 5: Pour in 200ml of coconut milk for creaminess and a subtle sweetness.\nStep 6: Use an immersion blender to blend the soup completely smooth. Alternatively, blend in batches in a regular blender — be careful with hot liquids.\nStep 7: Return to heat, taste, and adjust seasoning. Add a squeeze of lime juice to brighten the flavors.\nStep 8: Serve in warm bowls with a swirl of coconut milk, a sprinkle of toasted pumpkin seeds, and fresh coriander.', imageUrl: 'https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?w=600', cookingTime: 40, costLevel: 'Low', category: 'Zero Waste', isZeroWaste: true, sustainabilityTip: 'Use carrot tops in pesto or salad', ingredients: 'Carrot, Ginger, Onion, Coconut Milk, Broth, Lime', seoTitle: 'Carrot Ginger Soup', seoDescription: 'Creamy carrot ginger soup recipe', seoKeywords: 'carrot soup, ginger, vegan' },
    { title: 'Quinoa Buddha Bowl', description: 'Nutritious quinoa bowl with roasted vegetables', instructions: 'Step 1: Rinse 1 cup of quinoa under cold water for 1 minute to remove the bitter saponin coating. Cook in 2 cups of water with a pinch of salt — bring to a boil, then simmer covered for 15 minutes. Fluff with a fork.\nStep 2: Preheat oven to 200°C. Cube 1 medium sweet potato and toss with olive oil, cumin, paprika, salt, and pepper. Roast for 25 minutes until golden.\nStep 3: Drain and rinse 1 can of chickpeas. Toss with olive oil, garlic powder, and salt. Add to the oven for the last 15 minutes of the sweet potato roasting time.\nStep 4: Make the tahini dressing: whisk 3 tablespoons tahini, juice of 1 lemon, 1 minced garlic clove, 2 tablespoons water, and salt until smooth and pourable.\nStep 5: Wash and dry 2 large handfuls of baby spinach or mixed greens.\nStep 6: Assemble the bowls: start with a base of quinoa, then arrange the roasted sweet potato, crispy chickpeas, and fresh greens in separate sections.\nStep 7: Add sliced avocado and any other toppings you like — cucumber, cherry tomatoes, or pickled red onion all work well.\nStep 8: Drizzle generously with the tahini dressing and finish with sesame seeds and a squeeze of lemon.', imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600', cookingTime: 30, costLevel: 'Medium', category: 'Vegan', isZeroWaste: false, sustainabilityTip: 'Quinoa is a complete protein — great meat alternative', ingredients: 'Quinoa, Sweet Potato, Chickpeas, Spinach, Tahini, Lemon', seoTitle: 'Quinoa Buddha Bowl', seoDescription: 'Healthy quinoa buddha bowl recipe', seoKeywords: 'buddha bowl, quinoa, vegan' },
    { title: 'Chicken Soup', description: 'Classic comforting chicken noodle soup', instructions: 'Step 1: Place 1 whole chicken (or 4 bone-in thighs) in a large pot. Cover with 2 litres of cold water. Bring to a boil, then skim off any foam that rises to the surface.\nStep 2: Add 2 halved onions, 3 celery stalks, 2 carrots, 4 garlic cloves, 1 bay leaf, and 1 teaspoon of black peppercorns. Reduce heat to low.\nStep 3: Simmer gently for 45 minutes to 1 hour until the chicken is completely cooked and falling off the bone.\nStep 4: Remove the chicken and set aside to cool. Strain the broth through a fine mesh sieve and discard the spent vegetables.\nStep 5: Return the clear broth to the pot. Dice 2 fresh carrots and 2 celery stalks and add to the broth. Bring to a simmer.\nStep 6: Once the chicken is cool enough to handle, shred the meat into bite-sized pieces, discarding the skin and bones.\nStep 7: Add egg noodles or pasta to the simmering broth and cook according to package instructions.\nStep 8: Add the shredded chicken back to the pot, taste and adjust seasoning with salt and pepper, and serve hot with fresh parsley and crusty bread.', imageUrl: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=600', cookingTime: 45, costLevel: 'Medium', category: 'High Protein', isZeroWaste: true, sustainabilityTip: 'Use the whole chicken including bones for rich broth', ingredients: 'Chicken, Noodles, Carrot, Celery, Onion, Broth', seoTitle: 'Chicken Noodle Soup', seoDescription: 'Classic chicken noodle soup recipe', seoKeywords: 'chicken soup, comfort food, healthy' },
    { title: 'Mango Lassi', description: 'Refreshing Indian mango yogurt drink', instructions: 'Step 1: Use ripe, sweet mangoes for the best flavor. Peel and cube 2 large mangoes (or use 300g of frozen mango chunks for convenience).\nStep 2: Add the mango to a blender along with 200g of plain yogurt (full-fat for creaminess).\nStep 3: Add 150ml of cold whole milk. For a thicker lassi, use less milk; for a thinner, more drinkable consistency, add more.\nStep 4: Add 2 tablespoons of sugar (adjust to taste depending on the sweetness of your mangoes) and a pinch of ground cardamom.\nStep 5: Blend on high speed for 60 seconds until completely smooth and frothy.\nStep 6: Taste and adjust sweetness or cardamom. Add a pinch of salt if desired — it enhances the mango flavor.\nStep 7: Add a handful of ice cubes and blend for another 20 seconds for a chilled, frothy texture.\nStep 8: Pour into tall glasses and garnish with a pinch of cardamom, a few strands of saffron soaked in warm milk, or a small piece of mango on the rim.', imageUrl: 'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=600', cookingTime: 5, costLevel: 'Low', category: 'Quick Fix', isZeroWaste: true, sustainabilityTip: 'Use overripe mangoes that are too soft to eat', ingredients: 'Mango, Yogurt, Milk, Sugar, Cardamom, Ice', seoTitle: 'Mango Lassi', seoDescription: 'Refreshing mango lassi recipe', seoKeywords: 'mango lassi, drink, indian' },
]

const finalRecipes = [
    { title: 'Palak Paneer', description: 'Creamy spinach curry with cottage cheese', instructions: 'Step 1: Bring a large pot of water to a boil. Add 500g of fresh spinach and blanch for exactly 2 minutes until wilted and bright green. Immediately transfer to a bowl of ice water to stop cooking and preserve the color.\nStep 2: Drain the spinach and blend it into a smooth puree. Set aside.\nStep 3: Cut 250g of paneer into 2 cm cubes. Heat 2 tablespoons of oil in a pan and fry the paneer cubes on all sides until golden. Remove and set aside — do not overcook or they will become rubbery.\nStep 4: In the same pan, add 1 tablespoon of butter. Add 1 large finely diced onion and cook for 8 minutes until deep golden.\nStep 5: Add 1 tablespoon each of ginger and garlic paste. Cook for 2 minutes. Add 2 chopped tomatoes and cook for 5 minutes until soft.\nStep 6: Add 1 teaspoon cumin, 1 teaspoon coriander, half teaspoon garam masala, and half teaspoon chili powder. Stir for 1 minute.\nStep 7: Add the spinach puree and stir well. Simmer for 5 minutes. Add 3 tablespoons of cream and stir to combine.\nStep 8: Gently fold in the fried paneer cubes. Simmer for 3 more minutes. Serve hot with naan or rice.', imageUrl: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600', cookingTime: 35, costLevel: 'Medium', category: 'High Protein', isZeroWaste: false, sustainabilityTip: 'Spinach stems are edible — use them in the curry', ingredients: 'Spinach, Paneer, Onion, Tomato, Cream, Spices', seoTitle: 'Palak Paneer Recipe', seoDescription: 'Creamy palak paneer recipe', seoKeywords: 'palak paneer, indian, vegetarian' },
    { title: 'Biryani', description: 'Fragrant layered rice dish with chicken', instructions: 'Step 1: Marinate 1 kg bone-in chicken pieces: mix with 200g yogurt, 1 tablespoon each of ginger and garlic paste, 1 teaspoon red chili powder, 1 teaspoon garam masala, juice of 1 lemon, and salt. Marinate for at least 1 hour, ideally overnight.\nStep 2: Soak 2 cups of basmati rice in cold water for 30 minutes. Drain and parboil in heavily salted boiling water for exactly 6 minutes — the rice should be 70% cooked. Drain immediately.\nStep 3: Fry 2 large thinly sliced onions in oil until deep golden brown and crispy. This takes 15–20 minutes on medium heat. Drain on paper towels.\nStep 4: In a heavy-bottomed pot, heat 2 tablespoons of oil. Add the marinated chicken and cook on high heat for 5 minutes, stirring.\nStep 5: Layer half the parboiled rice over the chicken. Sprinkle half the fried onions, a few strands of saffron soaked in warm milk, and fresh mint leaves.\nStep 6: Add the remaining rice and top with the rest of the fried onions, saffron milk, and mint.\nStep 7: Cover the pot tightly with foil, then the lid. Cook on high heat for 5 minutes, then reduce to the lowest heat and cook for 20 minutes (dum cooking).\nStep 8: Remove from heat and let rest for 10 minutes before opening. Gently mix from the bottom and serve with raita and salad.', imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600', cookingTime: 60, costLevel: 'Medium', category: 'High Protein', isZeroWaste: false, sustainabilityTip: 'Use leftover biryani in wraps next day', ingredients: 'Chicken, Basmati Rice, Yogurt, Onion, Saffron, Spices', seoTitle: 'Chicken Biryani', seoDescription: 'Authentic chicken biryani recipe', seoKeywords: 'biryani, chicken, pakistani' },
    { title: 'Aloo Gobi', description: 'Spiced potato and cauliflower curry', instructions: 'Step 1: Cut 3 medium potatoes into 2 cm cubes and break 1 medium cauliflower into medium florets. Keep them roughly the same size for even cooking.\nStep 2: Heat 3 tablespoons of oil in a wide pan over medium-high heat. Add 1 teaspoon of cumin seeds and let them sizzle for 20 seconds.\nStep 3: Add 1 large finely diced onion and cook for 7 minutes until golden.\nStep 4: Add 1 teaspoon each of ginger and garlic paste. Cook for 1 minute.\nStep 5: Add 1 teaspoon turmeric, 1 teaspoon coriander powder, half teaspoon chili powder, and 1 chopped tomato. Cook for 3 minutes until the tomato softens.\nStep 6: Add the potatoes and stir to coat with the masala. Cook for 5 minutes.\nStep 7: Add the cauliflower florets and stir gently. Add 3 tablespoons of water, cover, and cook on medium-low heat for 20 minutes, stirring occasionally, until both vegetables are tender.\nStep 8: Uncover, increase heat to dry out any excess moisture. Taste and adjust salt. Garnish with fresh coriander and serve with roti.', imageUrl: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=600', cookingTime: 30, costLevel: 'Low', category: 'Vegan', isZeroWaste: true, sustainabilityTip: 'Use cauliflower leaves in the curry too', ingredients: 'Potato, Cauliflower, Onion, Tomato, Turmeric, Cumin', seoTitle: 'Aloo Gobi Recipe', seoDescription: 'Classic aloo gobi curry recipe', seoKeywords: 'aloo gobi, vegan, indian' },
    { title: 'Fruit Salad', description: 'Fresh seasonal fruit salad with honey dressing', instructions: 'Step 1: Choose a variety of fruits with different colors and textures for the best result. Good combinations include apple, banana, orange, grapes, strawberries, and kiwi.\nStep 2: Wash all fruits thoroughly. Peel and core the apple, peel the orange and separate into segments, peel and slice the banana, and halve the grapes.\nStep 3: Cut all fruits into similar bite-sized pieces so every spoonful has a mix.\nStep 4: Make the dressing: whisk together 1 tablespoon of honey, juice of half a lemon, and a pinch of ground ginger or mint.\nStep 5: Add the banana last — it browns quickly. Toss all fruits gently in a large bowl.\nStep 6: Pour the honey-lemon dressing over the fruit and toss gently to coat. The lemon juice also prevents browning.\nStep 7: Taste and add more honey if needed. The salad should be bright, sweet, and slightly tangy.\nStep 8: Refrigerate for 15 minutes before serving for the best flavor. Garnish with fresh mint leaves and serve chilled.', imageUrl: 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=600', cookingTime: 10, costLevel: 'Low', category: 'Quick Fix', isZeroWaste: true, sustainabilityTip: 'Use fruit peels for zest or compost', ingredients: 'Apple, Banana, Orange, Grapes, Honey, Lemon', seoTitle: 'Fresh Fruit Salad', seoDescription: 'Easy fresh fruit salad recipe', seoKeywords: 'fruit salad, healthy, dessert' },
    { title: 'Peanut Butter Smoothie', description: 'High protein peanut butter banana smoothie', instructions: 'Step 1: Freeze 2 ripe bananas the night before for the best thick, creamy texture. Peel and slice before freezing.\nStep 2: Add the frozen banana chunks to a blender.\nStep 3: Add 2 heaped tablespoons of natural peanut butter (the kind with no added sugar or oil).\nStep 4: Pour in 250ml of cold milk (dairy or oat milk both work well).\nStep 5: Add 3 tablespoons of rolled oats for extra fiber and staying power.\nStep 6: Add 1 tablespoon of honey and a pinch of cinnamon.\nStep 7: Blend on high speed for 60 seconds until completely smooth. If it is too thick, add more milk a splash at a time.\nStep 8: Pour into a large glass and optionally top with a drizzle of peanut butter, a sprinkle of granola, or a few banana slices. Drink immediately for the best texture.', imageUrl: 'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=600', cookingTime: 5, costLevel: 'Low', category: 'High Protein', isZeroWaste: false, sustainabilityTip: 'Peanuts use very little water to grow', ingredients: 'Peanut Butter, Banana, Milk, Oats, Honey', seoTitle: 'Peanut Butter Smoothie', seoDescription: 'High protein peanut butter smoothie', seoKeywords: 'smoothie, peanut butter, protein' },
]

const tipsData = [
    { ingredient: 'lemon', tip: "Don't toss the peels! Use them for zest in baking or soak in vinegar for a natural kitchen cleaner.", icon: '🍋' },
    { ingredient: 'bread', tip: 'Stale bread is perfect for homemade croutons or breadcrumbs. Just bake with a little olive oil.', icon: '🍞' },
    { ingredient: 'tomato', tip: 'Overripe tomatoes are excellent for homemade pasta sauce or salsas where texture matters less.', icon: '🍅' },
    { ingredient: 'potato', tip: 'Potato skins can be seasoned and baked into crispy chips. Never peel and waste again!', icon: '🥔' },
    { ingredient: 'banana', tip: 'Black spots mean more sugar. Perfect for smoothies or banana bread.', icon: '🍌' },
    { ingredient: 'egg', tip: 'Eggshells are rich in calcium — crush and add to soil as fertilizer for your plants.', icon: '🥚' },
    { ingredient: 'onion', tip: 'Onion skins make a rich, golden broth. Simmer with water for 20 mins and strain.', icon: '🧅' },
    { ingredient: 'spinach', tip: 'Wilted spinach is perfect for smoothies, soups, or sautéed as a side — still full of nutrients.', icon: '🥬' },
    { ingredient: 'rice', tip: 'Leftover rice makes the best fried rice. Day-old rice fries crispier than fresh.', icon: '🍚' },
    { ingredient: 'pasta', tip: 'Save pasta water — it\'s starchy gold for thickening sauces and making them cling to pasta.', icon: '🍝' },
    { ingredient: 'chicken', tip: 'Boil chicken bones for 4+ hours to make a rich, collagen-packed bone broth.', icon: '🍗' },
    { ingredient: 'apple', tip: 'Apple cores and peels can be simmered with cinnamon and sugar to make apple jelly.', icon: '🍎' },
    { ingredient: 'carrot', tip: 'Carrot tops are edible! Use them in pesto, chimichurri, or as a garnish.', icon: '🥕' },
    { ingredient: 'ginger', tip: 'Freeze ginger root and grate it directly from frozen — no peeling needed.', icon: '🫚' },
    { ingredient: 'coffee', tip: 'Used coffee grounds are excellent as a natural exfoliant or garden fertilizer.', icon: '☕' },
    { ingredient: 'avocado', tip: 'Rub the avocado pit on the surface of guacamole to prevent browning.', icon: '🥑' },
    { ingredient: 'garlic', tip: 'Garlic skins can be added to stocks for extra flavor. Never throw them away.', icon: '🧄' },
    { ingredient: 'broccoli', tip: 'Broccoli stems are just as nutritious as florets. Peel and slice them for stir fries.', icon: '🥦' },
    { ingredient: 'mushroom', tip: 'Mushroom stems make excellent stock. Dry them out and store for later use.', icon: '🍄' },
    { ingredient: 'cucumber', tip: 'Cucumber peels can be used in water for a refreshing infused drink.', icon: '🥒' },
]

const ingredientsData = [
    'Chicken', 'Rice', 'Lentils', 'Tomato', 'Onion', 'Garlic', 'Ginger', 'Spinach',
    'Carrot', 'Potato', 'Broccoli', 'Bell Pepper', 'Mushroom', 'Avocado', 'Banana',
    'Lemon', 'Olive Oil', 'Butter', 'Eggs', 'Milk', 'Yogurt', 'Cheese', 'Pasta',
    'Oats', 'Quinoa', 'Chickpeas', 'Black Beans', 'Coconut Milk', 'Soy Sauce', 'Honey',
]

const categoriesData = ['Zero Waste', 'High Protein', 'Budget Friendly', 'Quick Fix', 'Vegan']

const nutritionData: Record<string, { calories: number; protein: number; carbs: number; fat: number }> = {
    'Chicken Karahi': { calories: 420, protein: 38, carbs: 12, fat: 24 },
    'Daal Chawal': { calories: 380, protein: 18, carbs: 62, fat: 6 },
    'Vegetable Stir Fry': { calories: 220, protein: 8, carbs: 28, fat: 10 },
    'Egg Fried Rice': { calories: 350, protein: 14, carbs: 52, fat: 10 },
    'Grilled Chicken Salad': { calories: 310, protein: 42, carbs: 8, fat: 12 },
    'Banana Oat Pancakes': { calories: 280, protein: 10, carbs: 48, fat: 6 },
    'Spinach Smoothie': { calories: 180, protein: 6, carbs: 32, fat: 3 },
    'Lentil Soup': { calories: 260, protein: 16, carbs: 38, fat: 4 },
    'Avocado Toast': { calories: 320, protein: 8, carbs: 34, fat: 18 },
    'Chickpea Curry': { calories: 340, protein: 14, carbs: 44, fat: 12 },
    'Pasta Aglio e Olio': { calories: 420, protein: 12, carbs: 62, fat: 16 },
    'Overnight Oats': { calories: 310, protein: 12, carbs: 52, fat: 6 },
    'Tuna Salad Wrap': { calories: 380, protein: 32, carbs: 36, fat: 10 },
    'Mushroom Risotto': { calories: 440, protein: 14, carbs: 68, fat: 14 },
    'Black Bean Tacos': { calories: 290, protein: 12, carbs: 46, fat: 8 },
    'Greek Yogurt Bowl': { calories: 260, protein: 18, carbs: 34, fat: 6 },
    'Vegetable Soup': { calories: 180, protein: 6, carbs: 28, fat: 4 },
    'Salmon with Lemon': { calories: 380, protein: 44, carbs: 2, fat: 22 },
    'Hummus with Pita': { calories: 320, protein: 12, carbs: 42, fat: 14 },
    'Beef Stir Fry': { calories: 460, protein: 38, carbs: 22, fat: 24 },
    'Tomato Basil Pasta': { calories: 390, protein: 14, carbs: 58, fat: 12 },
    'Carrot Ginger Soup': { calories: 200, protein: 4, carbs: 32, fat: 8 },
    'Quinoa Buddha Bowl': { calories: 420, protein: 18, carbs: 56, fat: 14 },
    'Chicken Soup': { calories: 280, protein: 28, carbs: 22, fat: 8 },
    'Mango Lassi': { calories: 220, protein: 8, carbs: 42, fat: 4 },
    'Palak Paneer': { calories: 360, protein: 18, carbs: 14, fat: 26 },
    'Biryani': { calories: 520, protein: 32, carbs: 62, fat: 16 },
    'Aloo Gobi': { calories: 240, protein: 6, carbs: 38, fat: 8 },
    'Fruit Salad': { calories: 140, protein: 2, carbs: 34, fat: 1 },
    'Peanut Butter Smoothie': { calories: 380, protein: 16, carbs: 44, fat: 16 },
}

async function seed() {
    console.log('🌱 Seeding database...')
    await client.connect()

    // Categories
    console.log('Adding categories...')
    for (const name of categoriesData) {
        try { await db.insert(categories).values({ name }).onConflictDoNothing() } catch { }
    }

    // Ingredients
    console.log('Adding ingredients...')
    for (const name of ingredientsData) {
        try { await db.insert(ingredients).values({ name }).onConflictDoNothing() } catch { }
    }

    // Tips
    console.log('Adding tips...')
    for (const tip of tipsData) {
        try { await db.insert(tips).values(tip).onConflictDoNothing() } catch { }
    }

    // Clear existing recipes (nutrition cascades automatically)
    console.log('Clearing existing recipes...')
    await client.query('DELETE FROM nutrition')
    await client.query('DELETE FROM recipes')

    // Recipes
    console.log('Adding recipes...')
    const allRecipes = [...recipeData, ...moreRecipes, ...evenMoreRecipes, ...finalRecipes]
    for (const r of allRecipes) {
        try {
            const [inserted] = await db.insert(recipes).values({
                title: r.title, description: r.description, instructions: r.instructions,
                imageUrl: r.imageUrl, cookingTime: r.cookingTime, costLevel: r.costLevel,
                category: r.category, isZeroWaste: r.isZeroWaste, sustainabilityTip: r.sustainabilityTip,
                ingredients: r.ingredients, seoTitle: r.seoTitle, seoDescription: r.seoDescription, seoKeywords: r.seoKeywords,
            }).returning({ id: recipes.id })

            const nutr = nutritionData[r.title]
            if (nutr && inserted?.id) {
                await db.insert(nutrition).values({ recipeId: inserted.id, ...nutr })
            }
        } catch (e: any) { console.log(`Skipped ${r.title}: ${e.cause?.message || e.message}`) }
    }

    console.log('✅ Seed complete!')
    await client.end()
}

seed().catch(console.error)
